### ISSUE TITLE
Jobs not working

### ISSUE THREAD

**Issue by Exoboi** [Steffbeard/TW-Public#5]
The jobs plugin is not awarding cash to players or allowing players to switch jobs, giving an error that reads “An internal error occurred while attempting to preform this command”

I was mining and I wasn’t being awarded cash, and /jobs browse gives an error.

Yes, this bug can be done by using /jobs browse, or doing an action that should award cash

**Comment by Exoboi** [comment]
Maybe the jobs plugin is not the 1.14 version? Maybe it’s still the 1.12 version

**Comment by Steffbeard** [comment]
that's not the issue, it's the 1.14 version

**Comment by Exoboi** [comment]
Idk if this could help, but if the server is bukket, I remember seeing something about it not working/being rlly buggy, so it could be something to do with that?
